routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');


Route::resource('artist', 'ArtistController')->middleware('auth');
Route::resource('movie', 'MovieController')->middleware('auth');
Route::resource('cinema', 'CinemaController')->middleware('auth');
Route::resource('room', 'RoomController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

resources/views/movies/create.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Create Movies</h1>
    <form method="POST" action="{{ route('movie.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <p>
            <label for="title">Title</label>
            <input type="text" name="title" id="title" value="" required />
            <br>
            <label for="year">Year</label>
            <input type="number" name="year" id="year" value="" required />
            <br>
            <label for="artist_id">Realisateur</label>
            <select id="artist_id" name="artist_id">
                @foreach($artists as $artist)
                    <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                @endforeach
            </select>
            <label for="actor_id1">Acteur 1</label>
            <select id="actor_id1" name="actor_id1">
                @foreach($artists as $artist)
                    <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                @endforeach
            </select>
            <label for="actor_id2">Acteur 2</label>
            <select id="actor_id2" name="actor_id2">
                @foreach($artists as $artist)
                    <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                @endforeach
            </select>
            <br>
            <h4>Séance</h4>
            <label for="room_id">Room</label>
            <select id="room_id" name="room_id">
                @foreach($rooms as $room)
                    <option value="{{ $room->id }}">{{ $room->name }}</option>
                @endforeach
            </select>
            <label for="show_time">Show Time</label>
            <input id="show_time" name="show_time" type="datetime-local" value="2020-12-20T09:30"/>
            <br>
            <label for="img">Add an image:</label>
            <input type="file" id="img" name="img">
        </p>
        <button class="btn btn-success" type="submit">Create</button>
    </form>
@endsection

resources/views/movies/edit.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Edit Movies</h1>
    <form method="POST" action="{{ route('movie.update', $movie->id) }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <p>
            <label for="title">Title</label>
            <input type="text" name="title" id="title" value="{{ $movie->title }}" required/>
            <br>
            <label for="year">Year</label>
            <input type="number" name="year" id="year" value="{{ $movie->year }}" required/>
            <br>
            <label for="artist_id">Realisateur</label>
            <select id="artist_id" name="artist_id">
                @foreach($artists as $artist)
                    <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                @endforeach
            </select>
            <label for="actor_id1">Acteur 1</label>
            <select id="actor_id1" name="actor_id1">
                @foreach($artists as $artist)
                    @if($artist->id == $movie->actors->first()->id)
                        <option selected value="{{ $artist->id }}">{{ $artist->name }}</option>
                    @else
                        <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                    @endif
                @endforeach
            </select>
            <label for="actor_id2">Acteur 2</label>
            <select id="actor_id2" name="actor_id2">
                @foreach($artists as $artist)
                    @if($artist->id == $movie->actors->get(1)->id)
                        <option selected value="{{ $artist->id }}">{{ $artist->name }}</option>
                    @else
                        <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                    @endif
                @endforeach
            </select>
            <br>
            <h4>Séance</h4>
            <label for="room_id">Room</label>
            <select id="room_id" name="room_id">
                @foreach($rooms as $room)
                    @if($room->id == $movie->isPlayed->first()->id)
                        <option selected value="{{ $room->id }}">{{ $room->name }}</option>
                    @else
                        <option value="{{ $room->id }}">{{ $room->name }}</option>
                    @endif
                @endforeach
            </select>
            <label for="show_time">Show Time</label>
            <input id="show_time" name="show_time" type="datetime-local" value="{{$date}}"/>
            <br>
            <label for="img">Edit image:</label>
            <input class="d-inline" type="file" id="img" name="img">
            <p>
                <img src="/uploads/posters/poster_{{ $movie->id }}.png" alt="">
            </p>
        </p>
        <button class="btn btn-warning" type="submit">Update</button>
    </form>
@endsection

resources/views/movies/index.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>List Movies</h1>
    <table class="table table-striped table-centered">
        <thead>
            <tr>
                <th>{{ __('Title') }}</th>
                <th>{{ __('Year') }}</th>
                <th>{{ __('Real') }}</th>
                <th>{{ __('Image') }}</th>
                <th>{{ __('Actors') }}</th>
                <th>{{ __('Actions') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($movies as $movie)
            <tr>

                <td>{{ $movie->title }}</td>
                <td>{{ $movie->year }}</td>
                <td>{{ $movie->director->firstname }} {{ $movie->director->name }}</td>
                <td><img src="/uploads/posters/poster_{{ $movie->id }}.png" alt=""></td>
                <td>@foreach ($movie->actors as $actor)
                        {{ $actor->name }} {{ $actor->firstname }}<br>
                    @endforeach
                </td>
                <td class="table-action">
                    <a type="button" href="{{ route('movie.show', $movie->id) }}" class="btn btn-sm"
                       data-toggle="tooltip" title="@lang('Show movie') {{ $movie->title }}">
                        {{-- TODO: Ajouter un lien sur le nom des artiste pour le show à la place du bouton 'eye' --}}
                        <i class="far fa-eye"></i>
                    </a>
                    <a type="button" href="{{ route('movie.edit', $movie->id) }}" class="btn btn-sm"
                        data-toggle="tooltip" title="@lang('Edit movie') {{ $movie->title }}">
                        <i class="fas fa-edit fa-lg"></i>
                    </a>
                    <button type="button" onclick="remove(this)" href="{{ route('movie.destroy', $movie->id) }}" class="btn btn-danger btn-sm"
                        data-toggle="tooltip" title="@lang('Delete movie') {{ $movie->title }}">
                        <i class="fas fa-trash fa-lg"></i>
                    </button>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $movies->appends(request()->except('page'))->links() }}
    <br>
    <a href="movie/create" class="create">CREATE</a>
    <script>
        $.ajaxSetup({
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
        })
        function remove (e) {
            $.ajax({
                url: $(e).attr('href'),
                type: 'DELETE'
            }).done(function(){
                $(e).closest('tr').remove();
            })
            return false;
        }
    </script>
@endsection

resources/views/movies/show.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Show Movie</h1>
    <p>{{ $movie->title }}</p>
    <p>{{ $movie->year }}</p>
    <p>{{ $movie->director->firstname }} {{ $movie->director->name }}</p>
    <p><img src="/uploads/posters/poster_{{ $movie->id }}.png" alt=""></p>

    <h4>Actors :</h4>
    @foreach ($movie->actors as $actor)
        {{ $actor->name }} {{ $actor->firstname }}<br>
    @endforeach

    {{-- Boutons delete et edit --}}
    <br>
    <a type="button" href="{{ route('movie.edit', $movie->id) }}" class="btn btn-sm"
       data-toggle="tooltip" title="@lang('Edit movie') {{ $movie->name }}">
        <i class="fas fa-edit fa-lg"></i>
    </a>
    <button type="button" onclick="remove(this)" href="{{ route('movie.destroy', $movie->id) }}"
            class="btn btn-danger btn-sm"
            data-toggle="tooltip" title="@lang('Delete movie') {{ $movie->title }}">
        <i class="fas fa-trash fa-lg"></i>
    </button>
@endsection