routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');


Route::resource('artist', 'ArtistController')->middleware('auth');
Route::resource('movie', 'MovieController')->middleware('auth');
Route::resource('cinema', 'CinemaController')->middleware('auth');
Route::resource('room', 'RoomController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

app/Models/Artist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Artist extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'name', 'firstname', 'birthdate'
    ];
    public function has_directed() {
        return $this->hasMany('App\Models\Movie');
    }
    public function has_played() {
        return $this->belongsToMany('App\Models\Movie')->withPivot('role_name');
    }
}

app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artist;
use App\Http\Requests\ArtistRequest;
use Exception;
use Illuminate\Http\Response;
use Image;

use Illuminate\Http\Request;

class ArtistController extends Controller
{
    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        return view('artists.index', ['artists' => Artist::paginate(6)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('artists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArtistRequest $request
     * @return Response
     */
    public function store(ArtistRequest $request)
    {
        //
        $artist = Artist::create($request->all());
        $poster = $request->file('img');
        if ($poster) {
            $filename = 'face_' . $artist->id . '.' . $poster->getClientOriginalExtension();
            Image::make($poster)->fit(180, 240)
                ->save(public_path('/uploads/face/' . $filename));

        }
        return redirect()->route('artist.create')
            ->with('ok', __('Artist has been saved'));
    }

    /**
     * Display the specified resource.
     *
     * @param Artist $artist
     * @return Response
     */
    public function show(Artist $artist)
    {
        return view('artists.show', ['artist' => $artist]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Artist $artist
     * @return Response
     */
    public function edit(Artist $artist)
    {
        //
        return view('artists.edit', ['artist' => $artist]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArtistRequest $request
     * @param Artist $artist
     * @return Response
     */
    public function update(ArtistRequest $request, Artist $artist)
    {
        //
        $artist->update($request->all());

        $poster = $request->file('img');
        if ($poster) {
            $filename = 'face_' . $artist->id . '.' . $poster->getClientOriginalExtension();
            Image::make($poster)->fit(180, 240)
                ->save(public_path('/uploads/face/' . $filename));

        }

        return redirect()->route('artist.index')
            ->with('ok', __('Artist has been updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Artist $artist
     * @return Response
     * @throws Exception
     */
    public function destroy(Artist $artist)
    {
        //
        $artist->has_directed()->delete();
        $artist->has_played()->detach();
        $artist->delete();
        return response()->json();
    }
}

resources/views/artists/create.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Create Artist</h1>
    <form method="POST" action="{{ route('artist.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <p>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="" required />
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" id="firstname" value="" required />
            <br>
            <label for="birthdate">Birthdate</label>
            <input type="number" name="birthdate" id="birthdate" value="" required />
            <br>
            <label for="img">Add an image:</label>
            <input type="file" id="img" name="img">
        </p>
        <button class="btn btn-success" type="submit">Create</button>
    </form>
@endsection

resources/views/artists/edit.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Edit Artist</h1>
    <form method="POST" action="{{ route('artist.update', $artist->id) }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <p>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="{{ $artist->name }}" required/>
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" id="firstname" value="{{ $artist->firstname }}" required/>
            <br>
            <label for="birthdate">Birthdate</label>
            <input type="number" name="birthdate" id="birthdate" value="{{ $artist->birthdate }}" required/>
            <br>
            <label for="img">Add an image:</label>
            <input type="file" id="img" name="img">
        </p>

        <p><img src="/uploads/face/face_{{ $artist->id }}.png" alt=""></p>
        <button class="btn btn-warning" type="submit">Update</button>
    </form>
@endsection

resources/views/artists/index.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>List Artist</h1>
    <table class="table table-striped table-centered">
        <thead>
        <tr>
            <th>{{ __('Name') }}</th>
            <th>{{ __('Firstname') }}</th>
            <th>{{ __('Birthdate') }}</th>
            <th>{{ __('Image') }}</th>
            <th>{{ __('Actions') }}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($artists as $artist)
            <tr>
                <td>{{ $artist->name }}</td>
                <td>{{ $artist->firstname }}</td>
                <td>{{ $artist->birthdate }}</td>
                <td><img src="/uploads/face/face_{{ $artist->id }}.png" alt=""></td>
                <td class="table-action">
                    <a type="button" href="{{ route('artist.show', $artist->id) }}" class="btn btn-sm"
                       data-toggle="tooltip" title="@lang('Show artist') {{ $artist->name }}">
                        <i class="far fa-eye"></i>
                    </a>
                    <a type="button" href="{{ route('artist.edit', $artist->id) }}" class="btn btn-sm"
                       data-toggle="tooltip" title="@lang('Edit artist') {{ $artist->name }}">
                        <i class="fas fa-edit fa-lg"></i>
                    </a>
                    <button type="button" onclick="remove(this)" href="{{ route('artist.destroy', $artist->id) }}"
                            class="btn btn-danger btn-sm"
                            data-toggle="tooltip" title="@lang('Delete artist') {{ $artist->name }}">
                        <i class="fas fa-trash fa-lg"></i>
                    </button>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $artists->appends(request()->except('page'))->links() }}
    <br>
    <a href="artist/create" class="create">CREATE</a>
    <script>
        $.ajaxSetup({
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
        })

        function remove(e) {
            $.ajax({
                url: $(e).attr('href'),
                type: 'DELETE'
            }).done(function () {
                $(e).closest('tr').remove();
            })
            return false;
        }
    </script>
@endsection

resources/views/artists/show.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    {{--    TODO: SHOW ARTIST  afficher sa fiche détaillée  et filmographie--}}
    <h1>Show Artist</h1>
    <p>
        {{ $artist->name }}
        {{ $artist->firstname }}
        {{ $artist->birthdate }}
    </p>

    <p><img src="/uploads/face/face_{{ $artist->id }}.png" alt=""></p>

    <div>
        <h3>Filmographie</h3>
        @foreach ($artist->has_played as $movie)
            <p>
            {{ $movie->title}} <br>
                <img src="/uploads/posters/poster_{{ $movie->id }}.png" alt="">
            </p>
        @endforeach
    </div>
    <br>

    {{-- Boutons delete et edit --}}

    <a type="button" href="{{ route('artist.edit', $artist->id) }}" class="btn btn-sm"
       data-toggle="tooltip" title="@lang('Edit artist') {{ $artist->name }}">
        <i class="fas fa-edit fa-lg"></i>
    </a>
    <button type="button" onclick="remove(this)" href="{{ route('artist.destroy', $artist->id) }}"
            class="btn btn-danger btn-sm"
            data-toggle="tooltip" title="@lang('Delete artist') {{ $artist->name }}">
        <i class="fas fa-trash fa-lg"></i>
    </button>
    <br>
@endsection