routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');


Route::resource('artist', 'ArtistController')->middleware('auth');
Route::resource('movie', 'MovieController')->middleware('auth');
Route::resource('cinema', 'CinemaController')->middleware('auth');
Route::resource('room', 'RoomController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Room extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'name', 'capacity', 'cinema_id'
    ];
    public function owned() {
        return $this->belongsTo(Cinema::class, 'cinema_id');
    }

    public function play() {
        return $this->belongsToMany(Movie::class)->withPivot('show_time');
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cinema;
use App\Models\Room;
use App\Http\Requests\RoomRequest;

use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class RoomController extends Controller
{
    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        return view('rooms.index', ['rooms' => Room::paginate(6)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('rooms.create', ['cinemas' => Cinema::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RoomRequest $request
     * @return Response
     */
    public function store(RoomRequest $request)
    {
        //
        Room::create($request->all());
        return redirect()->route('room.create')
            ->with('ok', __('Room has been saved'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Room $room
     * @return Response
     */
    public function edit(Room $room)
    {
        //
        return view('rooms.edit', ['room' => $room, 'cinemas' => Cinema::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RoomRequest $request
     * @param Room $room
     * @return Response
     */
    public function update(RoomRequest $request, Room $room)
    {
        //
        $room->update($request->all());
        return redirect()->route('room.index')
            ->with('ok', __('Room has been updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Room $room
     * @return Response
     * @throws Exception
     */
    public function destroy(Room $room)
    {
        //
        $room->play()->detach();
        $room->delete();
        return response()->json();
    }
}

resources/views/rooms/create.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Create Room</h1>
    <form method="POST" action="{{ route('room.store') }}">
        {{ csrf_field() }}
        <p>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="" required />
            <label for="capacity">Capacity</label>
            <input type="number" name="capacity" id="capacity" value="" required />
            <select id="cinema_id" name="cinema_id">
                @foreach($cinemas as $cinema)
                    <option value="{{ $cinema->id }}">{{ $cinema->name }}</option>
                @endforeach
            </select>
        </p>
        <button class="btn btn-success" type="submit">Create</button>
    </form>
@endsection

resources/views/rooms/edit.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Edit Room</h1>
    <form method="POST" action="{{ route('room.update', $room->id) }}">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <p>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="{{ $room->name }}" required />
            <label for="capacity">Capacity</label>
            <input type="number" name="capacity" id="capacity" value="{{ $room->capacity }}" required />
            <select id="cinema_id" name="cinema_id">
                @foreach($cinemas as $cinema)
                    @if($cinema->id == $room->cinema_id)
                        <option selected value="{{ $cinema->id }}">{{ $cinema->name }}</option>
                    @else
                        <option value="{{ $cinema->id }}">{{ $cinema->name }}</option>
                    @endif
                @endforeach
            </select>
        </p>
        <button class="btn btn-warning" type="submit">Update</button>
    </form>
@endsection

resources/views/rooms/index.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>List Room</h1>
    <table class="table table-striped table-centered">
        <thead>
            <tr>
                <th>{{ __('Name') }}</th>
                <th>{{ __('Capacity') }}</th>
                <th>{{ __('Cinema') }}</th>
            </tr>
        </thead>
        <tbody>
        @foreach($rooms as $room)
            <tr>
                <td>{{ $room->name }}</td>
                <td>{{ $room->capacity }}</td>
                <td>{{ $room->owned->name }}</td>
                <td class="table-action">
                    <a type="button" href="{{ route('room.edit', $room->id) }}" class="btn btn-sm"
                        data-toggle="tooltip" title="@lang('Edit room') {{ $room->name }}">
                        <i class="fas fa-edit fa-lg"></i>
                    </a>
                    <button type="button" onclick="remove(this)" href="{{ route('room.destroy', $room->id) }}" class="btn btn-danger btn-sm"
                        data-toggle="tooltip" title="@lang('Delete room') {{ $room->name }}">
                        <i class="fas fa-trash fa-lg"></i>
                    </button>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $rooms->appends(request()->except('page'))->links() }}
    <br>
    <a href="room/create" class="create">CREATE</a>
    <script>
        $.ajaxSetup({
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
        })
        function remove (e) {
            $.ajax({
                url: $(e).attr('href'),
                type: 'DELETE'
            }).done(function(){
                $(e).closest('tr').remove();
            })
            return false;
        }
    </script>
@endsection