routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');


Route::resource('artist', 'ArtistController')->middleware('auth');
Route::resource('movie', 'MovieController')->middleware('auth');
Route::resource('cinema', 'CinemaController')->middleware('auth');
Route::resource('room', 'RoomController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

app/Models/Cinema.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cinema extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'name', 'street', 'npa', 'city', 'country'
    ];
    public function has_owned() {
        return $this->hasMany('App\Models\Room');
    }
}

app/Http/Controllers/CinemaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cinema;
use App\Http\Requests\CinemaRequest;

use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CinemaController extends Controller
{
    public function __construct() {
        $this->middleware('ajax')->only('destroy');
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        return view('cinemas.index', [ 'cinemas' => Cinema::paginate(6) ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('cinemas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CinemaRequest $request
     * @return Response
     */
    public function store(CinemaRequest $request)
    {
        //
        Cinema::create($request->all());
        return redirect()->route('cinema.create')
                        ->with('ok', __('Cinema has been saved'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Cinema  $cinema
     * @return Response
     */
    public function show(Cinema $cinema)
    {
        return view('cinemas.show', ['cinema' => $cinema]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Cinema $cinema
     * @return Response
     */
    public function edit(Cinema $cinema)
    {
        //
        return view('cinemas.edit', ['cinema' => $cinema]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CinemaRequest $request
     * @param Cinema $cinema
     * @return Response
     */
    public function update(CinemaRequest $request, Cinema $cinema)
    {
        //
        $cinema->update( $request->all() );
        return redirect()->route('cinema.index')
                        ->with( 'ok', __('Cinema has been updated') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Cinema $cinema
     * @return Response
     * @throws Exception
     */
    public function destroy(Cinema $cinema)
    {
        //
        $cinema->has_owned()->delete();
        $cinema->delete();
        return response()->json();
    }
}

resources/views/cinemas/create.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Create Cinema</h1>
    <form method="POST" action="{{ route('cinema.store') }}">
        {{ csrf_field() }}
        <p>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="" required />
            <br>
            <label for="street">Street</label>
            <input type="text" name="street" id="street" value="" required />
            <label for="npa">NPA</label>
            <input type="text" name="npa" id="npa" value="" required />
            <br>
            <label for="city">City</label>
            <input type="text" name="city" id="city" value="" required />
            <label for="country">Country</label>
            <input type="text" name="country" id="country" value="" required />
        </p>
        <button class="btn btn-success" type="submit">Create</button>
    </form>
@endsection

resources/views/cinemas/edit.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>Edit Cinema</h1>
    <form method="POST" action="{{ route('cinema.update', $cinema->id) }}">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <p>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="{{ $cinema->name }}" required />
            <br>
            <label for="street">Street</label>
            <input type="text" name="street" id="street" value="{{ $cinema->street }}" required />
            <label for="npa">NPA</label>
            <input type="text" name="npa" id="npa" value="{{ $cinema->npa }}" required />
            <br>
            <label for="city">City</label>
            <input type="text" name="city" id="city" value="{{ $cinema->city }}" required />
            <label for="country">Country</label>
            <input type="text" name="country" id="country" value="{{ $cinema->country }}" required />
        </p>
        <button class="btn btn-warning" type="submit">Update</button>
    </form>
@endsection

resources/views/cinemas/index.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    <h1>List Cinema</h1>
    <table class="table table-striped table-centered">
        <thead>
            <tr>
                <th>{{ __('Name') }}</th>
                <th>{{ __('Street') }}</th>
                <th>{{ __('NPA') }}</th>
                <th>{{ __('City') }}</th>
                <th>{{ __('Country') }}</th>
            </tr>
        </thead>
        <tbody>
        @foreach($cinemas as $cinema)
            <tr>
                <td>{{ $cinema->name }}</td>
                <td>{{ $cinema->street }}</td>
                <td>{{ $cinema->npa }}</td>
                <td>{{ $cinema->city }}</td>
                <td>{{ $cinema->country }}</td>
                <td class="table-action">
                    <a type="button" href="{{ route('cinema.show', $cinema->id) }}" class="btn btn-sm"
                       data-toggle="tooltip" title="@lang('Show cinema') {{ $cinema->name }}">
                        {{-- TODO: Ajouter un lien sur le nom des cinemas pour le show à la place ou en plus du bouton 'eye' --}}
                        <i class="far fa-eye"></i>
                    </a>
                    <a type="button" href="{{ route('cinema.edit', $cinema->id) }}" class="btn btn-sm"
                        data-toggle="tooltip" title="@lang('Edit cinema') {{ $cinema->name }}">
                        <i class="fas fa-edit fa-lg"></i>
                    </a>
                    <button type="button" onclick="remove(this)" href="{{ route('cinema.destroy', $cinema->id) }}" class="btn btn-danger btn-sm"
                        data-toggle="tooltip" title="@lang('Delete cinema') {{ $cinema->name }}">
                        <i class="fas fa-trash fa-lg"></i>
                    </button>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $cinemas->appends(request()->except('page'))->links() }}
    <br>
    <a href="cinema/create" class="create">CREATE</a>
    <script>
        $.ajaxSetup({
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
        })
        function remove (e) {
            $.ajax({
                url: $(e).attr('href'),
                type: 'DELETE'
            }).done(function(){
                $(e).closest('tr').remove();
            })
            return false;
        }
    </script>
@endsection

resources/views/cinemas/show.blade.php
@extends('layouts.app')
@section('title', 'Laravel')
@section('content')
    {{--    TODO: SHOW cinemas  permettant d'afficher la fiche détaillée d'un cinéma (liste des salles, films à l'affiche, liste des séances)--}}
    <h1>Show Cinema</h1>
    <p>{{ $cinema->name }}</p>
    <p>{{ $cinema->street }}</p>
    <p>{{ $cinema->npa }}</p>
    <p>{{ $cinema->city }}</p>
    <p>{{ $cinema->country }}</p>



    @foreach ($cinema->has_owned as $room)
        {{--        <p>--}}
        <h3>{{ $room->name}}</h3>
        <h4>Séances</h4>

        <hr>

        @if($room->play->isEmpty())
            <p>Aucune séance programmée</p>

            <hr>
        @endif

        @foreach($room->play as $seances)
            <img src="/uploads/posters/poster_{{ $seances->id }}.png" alt=""><br>
            - Movie : {{ $seances->title }}<br>
            - Date : {{ $seances->pivot->show_time }}
            <hr>
        @endforeach
    @endforeach


    {{-- Boutons delete et edit --}}

    <a type="button" href="{{ route('cinema.edit', $cinema->id) }}" class="btn btn-sm"
       data-toggle="tooltip" title="@lang('Edit cinema') {{ $cinema->name }}">
        <i class="fas fa-edit fa-lg"></i>
    </a>
    <button type="button" onclick="remove(this)" href="{{ route('cinema.destroy', $cinema->id) }}"
            class="btn btn-danger btn-sm"
            data-toggle="tooltip" title="@lang('Delete cinema') {{ $cinema->name }}">
        <i class="fas fa-trash fa-lg"></i>
    </button>
@endsection